name: backend-ci

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout Code

      - uses: actions/setup-python@v5
        name: Setup Python
        with:
          python-version: '3.10'

      - run: |
          pip install --user pipenv flake8
          pipenv install
        name: Install Dependencies
        working-directory: starter/backend

      - run: pipenv run lint
        name: Run Linter
        working-directory: starter/backend

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout Code

      - uses: actions/setup-python@v5
        name: Setup Python
        with:
          python-version: '3.10'

      - run: |
          pip install --user pipenv
          pipenv install
        name: Install Dependencies
        working-directory: starter/backend

      - run: pipenv run test
        name: Run Tests
        working-directory: starter/backend

  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout Code

      - uses: actions/setup-python@v5
        name: Setup Python
        with:
          python-version: '3.10'

      - run: |
          pip install --user pipenv
          pipenv install
        name: Install Dependencies
        working-directory: starter/backend

      - run: docker build -t mp-backend:latest .
        name: Build Docker Image
        working-directory: starter/backend

      - run: docker run -d -p 5000:5000 --name mp-backend mp-backend
        name: Run Docker Container
        working-directory: starter/backend